-d /workspaces/Trivius/project/trivius/impl/gwsynthesis/trivius.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /workspaces/Trivius/trivius.cst
-cfg /workspaces/Trivius/project/trivius/impl/pnr/device.cfg
-sdc /workspaces/Trivius/trivius.sdc
-bit
-tr
-ph
-timing
-oreg_not_in_iob
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 48.000
